"use client";
import { useState } from "react";

type CredentialDescriptorJson={id:string;type?:PublicKeyCredentialType;transports?:AuthenticatorTransport[]};
type CreationOptionsJson=Omit<PublicKeyCredentialCreationOptions,"challenge"|"user"|"excludeCredentials">&{challenge:string;user:Omit<PublicKeyCredentialUserEntity,"id">&{id:string};excludeCredentials?:CredentialDescriptorJson[]};
type RequestOptionsJson=Omit<PublicKeyCredentialRequestOptions,"challenge"|"allowCredentials">&{challenge:string;allowCredentials?:CredentialDescriptorJson[]};
type CeremonyStart<T>={challengeId:string;options:T};

export function PasskeyRegistration(){const[state,setState]=useState("");async function run(){try{setState("Passkey isteği hazırlanıyor…");const start=await api<CeremonyStart<CreationOptionsJson>>("/api/security/passkeys/registration-options",{});const publicKey=creationOptions(start.data.options);const credential=await navigator.credentials.create({publicKey}) as PublicKeyCredential|null;if(!credential)throw new Error("PASSKEY_CANCELLED");await api("/api/security/passkeys/registration-verify",{challengeId:start.data.challengeId,label:"Bu cihaz",response:credentialJson(credential)});setState("Passkey güvenle kaydedildi.");location.reload()}catch(error){setState(error instanceof Error?error.message:"PASSKEY_FAILED")}}return <div className="stack"><button className="button" type="button" onClick={run}>Bu cihaza passkey kaydet</button><output aria-live="polite">{state}</output></div>}

export function PasskeyLogin(){const[state,setState]=useState("");async function run(){try{const email=(document.querySelector<HTMLInputElement>('input[name="email"]')?.value??"").trim();if(!email)throw new Error("E-posta gerekli");setState("Passkey bekleniyor…");const start=await api<CeremonyStart<RequestOptionsJson>>("/api/auth/passkey/options",{email});const publicKey=requestOptions(start.data.options);const credential=await navigator.credentials.get({publicKey}) as PublicKeyCredential|null;if(!credential)throw new Error("PASSKEY_CANCELLED");await api("/api/auth/passkey/verify",{challengeId:start.data.challengeId,credentialId:credential.id,response:credentialJson(credential)});location.href="/"}catch(error){setState(error instanceof Error?error.message:"PASSKEY_FAILED")}}return <div className="stack"><button className="button secondary" type="button" onClick={run}>Passkey ile giriş</button><output className="error" aria-live="polite">{state}</output></div>}

export function RecoveryCodeRotation(){const[codes,setCodes]=useState<string[]>([]);const[state,setState]=useState("");async function run(){if(!confirm("Eski kurtarma kodları hemen iptal edilecek. Devam edilsin mi?"))return;try{const result=await api<{codes:string[]}>("/api/security/recovery-codes",{});setCodes(result.data.codes);setState("Kodlar yalnız bu kez gösterilir. Güvenli yerde saklayın.")}catch(error){setState(error instanceof Error?error.message:"RECOVERY_FAILED")}}return <div className="stack"><button className="button danger" type="button" onClick={run}>Kurtarma kodlarını yenile</button><output aria-live="polite">{state}</output>{codes.length?<pre className="json">{codes.join("\n")}</pre>:null}</div>}

async function api<T=unknown>(url:string,body:unknown):Promise<{data:T}>{const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json","accept":"application/json"},body:JSON.stringify(body)});const json=await response.json() as {ok:boolean;code?:string;data:T};if(!response.ok||!json.ok)throw new Error(json.code??"PLATFORM_REQUEST_FAILED");return json}
function decode(value:string){const normalized=value.replace(/-/g,"+").replace(/_/g,"/");const raw=atob(normalized.padEnd(Math.ceil(normalized.length/4)*4,"="));return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function encode(value:ArrayBuffer){let raw="";for(const byte of new Uint8Array(value))raw+=String.fromCharCode(byte);return btoa(raw).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function creationOptions(value:CreationOptionsJson):PublicKeyCredentialCreationOptions{return{...value,challenge:decode(value.challenge),user:{...value.user,id:decode(value.user.id)},excludeCredentials:(value.excludeCredentials??[]).map(x=>({...x,type:"public-key",id:decode(x.id)}))}}
function requestOptions(value:RequestOptionsJson):PublicKeyCredentialRequestOptions{return{...value,challenge:decode(value.challenge),allowCredentials:(value.allowCredentials??[]).map(x=>({...x,type:"public-key",id:decode(x.id)}))}}
function credentialJson(credential:PublicKeyCredential){const response=credential.response;return{id:credential.id,rawId:encode(credential.rawId),type:credential.type,authenticatorAttachment:credential.authenticatorAttachment,clientExtensionResults:credential.getClientExtensionResults(),response:response instanceof AuthenticatorAttestationResponse?{clientDataJSON:encode(response.clientDataJSON),attestationObject:encode(response.attestationObject),transports:response.getTransports?.()??[]}:response instanceof AuthenticatorAssertionResponse?{clientDataJSON:encode(response.clientDataJSON),authenticatorData:encode(response.authenticatorData),signature:encode(response.signature),userHandle:response.userHandle?encode(response.userHandle):undefined}:{}}}
