import { getPlatformOrganization360 } from "@tilbecore/platform";
import type { OrganizationId } from "@tilbecore/contracts";
import { AdminShell, JsonPanel, PageHead } from "../../../src/components";
import { pageActor } from "../../../src/page-auth";
import { platformRepository } from "../../../src/platform-server";
import { TenantAdminInvitationForm } from "../../../src/invitation-client";

export const dynamic = "force-dynamic";
export default async function Organization360Page({ params }: { params: Promise<{ id:string }> }) {
  const actor=await pageActor("platform.organization.read"); const {id}=await params; const repository=platformRepository(); const data=await getPlatformOrganization360(repository,actor,id as OrganizationId);const[configuration,operations]=await Promise.all([repository.organizationConfiguration(id as OrganizationId),repository.listOrganizationOperations(id as OrganizationId)]);
  const sections=[
    ["overview","Genel özet",{id:data.id,tenantInstanceId:data.tenantInstanceId,status:data.status,domain:data.domain,databaseStatus:data.databaseStatus,criticalAlert:data.criticalAlert}],
    ["lifecycle","Yaşam döngüsü",data.lifecycleEvents], ["license","Plan, lisans ve entitlement",data.license],
    ["domains","Domain ve custom domain",data.domains], ["provisioning","Provisioning işleri",data.provisioningJobs],
    ["database","Tenant DB ve migration",data.tenant], ["admins","Firma Admin davetleri",data.adminInvitations],
    ["configuration","Yapılandırma ve sürüm farkları",configuration], ["operations","Dışa aktarma, kapatma ve devir işleri",operations],
    ["backups","Backup / restore",data.backups], ["support","SupportSession",data.supportSessions], ["audit","Audit ve olay geçmişi",data.auditEvents],
  ] as const;
  return <AdminShell><PageHead title={`${data.displayName} 360°`} description={`${data.slug} · ${data.status}`} /><nav className="tabs">{sections.map(([key,label])=><a key={key} href={`#${key}`}>{label}</a>)}</nav><section className="stack">{sections.map(([key,label,value])=><article className="card" id={key} key={key}><h2>{label}</h2><JsonPanel value={value}/>{key==="admins"&&data.tenantInstanceId?<TenantAdminInvitationForm organizationId={data.id} tenantInstanceId={data.tenantInstanceId}/>:null}{key==="operations"?operations.map(item=><div key={String(item.id)}>{item.status==="awaiting_approval"?<form action={`/api/organization-operations/${String(item.id)}/approve`} method="post"><button className="button">İkinci yetkili olarak onayla</button></form>:null}{["pending","awaiting_approval","approved"].includes(String(item.status))?<form action={`/api/organization-operations/${String(item.id)}/cancel`} method="post"><button className="button danger">İşi iptal et</button></form>:null}</div>):null}</article>)}<article className="card"><h2>Kontrollü firma işlemi</h2><p>Kritik işten önce Güvenlik sayfasında yeniden doğrulama gerekir. Kapatma, export ve devir farklı ikinci yetkili ister.</p><form className="form-grid" action={`/api/organizations/${data.id}/operations`} method="post"><input type="hidden" name="tenantInstanceId" value={data.tenantInstanceId}/><label>İşlem<select name="type"><option value="freeze">Firma dondurma</option><option value="reactivate">Yeniden etkinleştirme</option><option value="closure_precheck">Kapatma ön kontrolü</option><option value="closure_request">Kapatma talebi</option><option value="data_export">Veri dışa aktarma talebi</option><option value="ownership_transfer">Yönetim devri</option></select></label><label>Idempotency anahtarı<input name="idempotencyKey" required minLength={8}/></label><label>Yeni sahip/yönetici referansı<input name="targetOwnerRef"/></label><label>Gerekçe<textarea name="reason" required minLength={8}/></label><button className="button">Kontrollü işi başlat</button></form></article><article className="card"><h2>Yaşam döngüsü işlemi</h2><form className="form-grid" action={`/api/organizations/${data.id}/lifecycle`} method="post"><input type="hidden" name="fromStatus" value={data.status}/><input type="hidden" name="expectedVersion" value={data.version}/><label>Yeni durum<select name="toStatus" required>{["provisioning","active","suspended","restricted","archived","provisioning_failed"].map(x=><option key={x}>{x}</option>)}</select></label><label>Neden<textarea name="reason" required minLength={8}/></label><label>Etki özeti<textarea name="impactSummary" required minLength={8}/></label><button className="button" type="submit">Onaylı geçişi uygula</button></form></article></section></AdminShell>;
}
